import { faHtml5, faCss3Alt, faSquareJs, faPython, faReact, faNode, faGit } from '@fortawesome/free-brands-svg-icons'
import { ISkills } from '../models/ISkills'

export const skillsEN: ISkills[] = [
    { id: 1, title: "HTML", icon: faHtml5, description: 'Proficient in using HTML to structure web content with semantic tags, ensuring accessibility and compatibility across various browsers. Skilled in creating well-organized, SEO-friendly web pages.' },
    { id: 2, title: "CSS / SASS", icon: faCss3Alt, description: 'Experienced in styling web applications with CSS, including responsive design techniques. Proficient in SASS to streamline and maintain complex stylesheets, ensuring consistency and ease of maintenance.' },
    { id: 3, title: "JavaScript / Typescript", icon: faSquareJs, description: 'Adept at utilizing JavaScript to create dynamic and interactive web experiences. Proficient in TypeScript, enhancing code quality and maintainability by adding static typing to JavaScript projects. Skilled in working with modern JavaScript frameworks and libraries.' },
    { id: 4, title: "Python", icon: faPython, description: 'Proficient in Python, a versatile programming language. Skilled in leveraging Python for a variety of applications, including data analysis using Pandas, web development with Django, and game development using PyGame. Capable of implementing complex solutions across multiple domains, from data manipulation to creating robust web applications and engaging 2D games.' },
    { id: 5, title: "React / Next.js", icon: faReact, description: 'Experienced in building web applications with React, a powerful JavaScript library for creating user interfaces. Familiar with Next.js, a framework that enhances React applications with server-side rendering, SEO optimization, and routing capabilities.' },
    { id: 6, title: "Node.js", icon: faNode, description: 'Competent in server-side development using Node.js, enabling the creation of scalable, efficient backend applications and APIs. Proficient in utilizing npm packages and building server-side logic for web projects.' },
]

export const skillsCZ: ISkills[] = [
    { id: 1, title: "HTML", icon: faHtml5, description: 'Znalost používání HTML ke strukturování webového obsahu pomocí sémantických značek, zajištění dostupnosti a kompatibility napříč různými prohlížeči. Zkušenosti s tvorbou dobře organizovaných webových stránek šetrných k SEO.' },
    { id: 2, title: "CSS / SASS", icon: faCss3Alt, description: 'Zkušenosti se stylováním webových aplikací pomocí CSS, včetně technik responzivního návrhu. Znalost SASS pro zefektivnění a údržbu složitých stylů, zajištění konzistence a snadné údržby.' },
    { id: 3, title: "JavaScript / Typescript", icon: faSquareJs, description: 'Zběhlý ve využívání JavaScriptu k vytváření dynamických a interaktivních webových zážitků. Znalost TypeScript, zlepšení kvality kódu a jeho udržovatelnosti přidáním statického psaní do projektů JavaScriptu. Zkušenosti v práci s moderními JavaScriptovými frameworky a knihovnami.' },
    { id: 4, title: "Python", icon: faPython, description: 'Znalost Pythonu, všestranného programovacího jazyka. Zkušenosti s využitím Pythonu pro různé aplikace, včetně analýzy dat pomocí Pandas, vývoje webu s Django a vývoje her pomocí PyGame. Schopnost implementovat komplexní řešení napříč více doménami, od manipulace s daty po vytváření robustních webových aplikací a poutavých 2D her.' },
    { id: 5, title: "React / Next.js", icon: faReact, description: 'Zkušenosti s vytvářením webových aplikací pomocí React, výkonné JavaScriptové knihovny pro vytváření uživatelských rozhraní. Známe Next.js, framework, který vylepšuje aplikace React o vykreslování na straně serveru, SEO optimalizaci a možnosti směrování.' },
    { id: 6, title: "Node.js", icon: faNode, description: 'Kompetentní ve vývoji na straně serveru pomocí Node.js, umožňující vytváření škálovatelných, efektivních backendových aplikací a API. Dokonalý ve využívání balíčků npm a budování logiky na straně serveru pro webové projekty.' },
]

export const skillsRU: ISkills[] = [
    { id: 1, title: "HTML", icon: faHtml5, description: 'Опыт использования HTML для структурирования веб-контента с помощью семантических тегов, обеспечения доступности и совместимости в различных браузерах. Умение создавать хорошо организованные, оптимизированные для SEO веб-страницы.' },
    { id: 2, title: "CSS / SASS", icon: faCss3Alt, description: 'Имеет опыт стилизации веб-приложений с помощью CSS, включая методы адаптивного дизайна. Владение SASS для оптимизации и поддержки сложных таблиц стилей, обеспечения согласованности и простоты обслуживания.' },
    { id: 3, title: "JavaScript / Typescript", icon: faSquareJs, description: 'Владеет использованием JavaScript для создания динамичных и интерактивных веб-приложений. Владение TypeScript, повышение качества и удобства обслуживания кода за счет добавления статической типизации в проекты JavaScript. Умение работать с современными JavaScript-фреймворками и библиотеками.' },
    { id: 4, title: "Python", icon: faPython, description: 'Знание Python – универсального языка программирования. Имеет навыки использования Python для различных приложений, включая анализ данных с помощью Pandas, веб-разработку с помощью Django и разработку игр с использованием PyGame. Способен внедрять сложные решения в различных областях: от манипулирования данными до создания надежных веб-приложений и увлекательных 2D-игр.' },
    { id: 5, title: "React / Next.js", icon: faReact, description: 'Имеет опыт создания веб-приложений с помощью React, мощной библиотеки JavaScript для создания пользовательских интерфейсов. Знакомство с Next.js, фреймворком, который расширяет приложения React за счет серверного рендеринга, SEO-оптимизации и возможностей маршрутизации.' },
    { id: 6, title: "Node.js", icon: faNode, description: 'Компетентен в разработке серверной части с использованием Node.js, что позволяет создавать масштабируемые и эффективные серверные приложения и API. Опыт использования пакетов npm и построения серверной логики для веб-проектов.' },
]